[[Torch]]
arch = "aarch64"
git-tree-sha1 = "54f27bd1c37f3aba55fbf4e7bf16b61c6647af2d"
os = "macos"

    [[Torch.download]]
    sha256 = "480521af83aa94a0b26522df6fe304ff8a33d246a323d7dbc9fdd636d97cfbd0"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.aarch64-apple-darwin.tar.gz"
[[Torch]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb4829a7f63f04724aaa999654b01c06832c40c9"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "b58317e91d704b8c13c1b31fa02875d72b628ffcf81d121269c40f5eaea19b4d"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Torch]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b38656d13e0c0429b24fc5e83e6c9cf8a7f4a7a"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "6ec5f441af30ce500fadbb760e11e35117bfd861002a8497737374f9b3519327"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Torch]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d495d26af7955c3087e342e63d6b7defb1b8984"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "ee5dbc8aa6c1a6ed4e2a681ac140291bce678a8773f6d561692865c0362c4750"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.i686-linux-gnu-cxx03.tar.gz"
[[Torch]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "431d5198e0bbf5e4aae8abf4ebece6d6497c95d2"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "84618db00396cbe67757040a37e4c09425fe31bcd5126bd44da111bb98916917"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Torch]]
arch = "x86_64"
git-tree-sha1 = "4676c2656c85d54b21443f187ef8509ff5b5eb2a"
os = "macos"

    [[Torch.download]]
    sha256 = "1782377dd75ce6be5a46b745fe4ad5beafd5e2c5f0456065f30c9b2cfabc2353"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-apple-darwin.tar.gz"
[[Torch]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1faf9a0d630f2f82fd174b5584b40e973e4e5354"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "6c273fef404b7cee753d3dca31d18c1479dfc684e8d8ea41840de4d6d182d331"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "10.2"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08aba3879795af39352ce45175251751e3721ea1"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "ea9ccc9776780fb657c08366b2af41f00bfc1e82f039ca485dedc00508a0b077"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx03-cuda+10.2.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95c6bfac03fa36c42cd99100cbb8cd42e296ad1e"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "89461d619e472cdb50df7f5283742157b9958dbcd89055968c132c4170f164a4"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx03-cuda+11.3.tar.gz"
[[Torch]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "256a051afb804ffda6cf05b5196bf8ef27afce74"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "d6ff8110bf5cf9c5c5c5730c86c05a16eb31f7d3cdf22f98ac1c70adc3d4795e"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "10.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a66f1779b3653336a3603abf80870df8897023cd"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "c44913ae0b39d339c3d2d6c28d6e163677384f7496e27766bfa7c833ce33cb52"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx11-cuda+10.2.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "929e07419d06d190327bd30982e5b0b510a49664"
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "7b9d898f1913ca2a9b8fc5b1908c3469b805b6c5d2dd06976090f5576cdc96bb"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+0/Torch.v1.10.2.x86_64-linux-gnu-cxx11-cuda+11.3.tar.gz"
