[[Torch]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9302210a00165e6a71a219b46d1704f79295824d"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "8183cef07fc29cd7d60b21bde82436cfd3a1e4a10f985c5f849f46706135e7da"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.i686-linux-gnu-cxx03.tar.gz"
[[Torch]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d5f33afd0f8354a35e955945b6e709baa6ca0be"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "7a6ef79d8c617d7e96f39dc7e0ab7001ef4e52684a815254f67255cf36e25dd0"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e40d662589bc2752ec2c94c3cb0105349bebd47"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "1825ad0fea82c37a71f0e88f6f5330fd98b3f65464c098a509c675b12798df39"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx03-cuda+none.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f6dc97944f8487286deebdbe764cd776df6965a"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "4dfa78041fcc1e1b066d940b24950dcb672010d6321cdd4bd80766e059b924c1"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[Torch]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93011e12ef074c8a104bd98c4d28c3c0fe9544a6"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "cb37ac73f46ad75be6fb094b4e99aa0b8941519c3e27bc6365dc05377c664358"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Torch]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be2f4c32e564d791a2fed5180f072922d9cf6a2b"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "9fdd4b73737698b7e297690bf7b8fb2f3f89a6425c84a8ec724c7e16a0507022"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Torch]]
arch = "x86_64"
git-tree-sha1 = "c52da90f09fa4cfdcdfc8f8aee5085c71024c631"
lazy = true
os = "macos"

    [[Torch.download]]
    sha256 = "d38048c63e09d21338de85a76bba781eee0eb86e0eb3402e70401418ef7b717a"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-apple-darwin.tar.gz"
[[Torch]]
arch = "aarch64"
git-tree-sha1 = "e34aada1d8303c29ea8aedbe523688ca71cc5f65"
lazy = true
os = "macos"

    [[Torch.download]]
    sha256 = "249cd9e28cb1da3a1f9a67ab29cca861b792127da0b230ce8e50ce50a889c2e2"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.aarch64-apple-darwin.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "10.2"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d55d5e46605b798bab0a5662d679a048523ae2eb"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "700086e2660c1d1f8dc59792878f9cd03efd37a8cd478ede428485a58a1b9116"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx03-cuda+10.2.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "10.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9dafbaae4f0f96a9531fb62d87b373e6541600"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "95ff2d8f5b70db3926177e2305b866b0711a55d37eff602817194bdc5b75bcd8"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx11-cuda+10.2.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "649afffafd48e5c4b92718721e2b6628dd95c89f"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "cc5fdcde1f1fe0a0b8855555c4884587f6ee1889f59c18a4398cc5f7424cc8da"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx03-cuda+11.3.tar.gz"
[[Torch]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df751aad1e240ec7b9143977a6bd097fe1af3764"
lazy = true
libc = "glibc"
os = "linux"

    [[Torch.download]]
    sha256 = "099c0fbbea7c9c7106fbd56a57952975edfae305266993ee6e3abd46b17789e2"
    url = "https://github.com/JuliaBinaryWrappers/Torch_jll.jl/releases/download/Torch-v1.10.2+1/Torch.v1.10.2.x86_64-linux-gnu-cxx11-cuda+11.3.tar.gz"
