# Autogenerated wrapper script for Torch_jll for x86_64-apple-darwin
export libtorch, libtorch_cpu

using CompilerSupportLibraries_jll
using CPUInfo_jll
using Gloo_jll
using MKL_jll
using PThreadPool_jll
using SLEEF_jll
using XNNPACK_jll
using protoc_jll
JLLWrappers.@generate_wrapper_header("Torch")
JLLWrappers.@declare_library_product(libtorch, "@rpath/libtorch.1.10.dylib")
JLLWrappers.@declare_library_product(libtorch_cpu, "@rpath/libtorch_cpu.1.10.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, CPUInfo_jll, Gloo_jll, MKL_jll, PThreadPool_jll, SLEEF_jll, XNNPACK_jll, protoc_jll)
    JLLWrappers.@init_library_product(
        libtorch,
        "lib/libtorch.1.10.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtorch_cpu,
        "lib/libtorch_cpu.1.10.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
